export const AUTH = {
  FAILED: 'FAILED',
  IN_PROGRESS: 'IN_PROGRESS',
  LOGOUT: 'LOGOUT',
  SUCCESS: 'SUCCESS'
}

export const NAVIGATION = {
  ADD_VISIBLE: 'ADD_VISIBLE',
  REMOVE_VISIBLE: 'REMOVE_VISIBLE'
}

export const TOAST = {
  TOGGLE: 'TOAST.TOGGLE'
}
